version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: office-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: office-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
