version: '3.8'

services:

  office-backend:
    build:
      context: ./backend
    container_name: office-backend
    ports:
      - "5000:5000"
    restart: always

  office-frontend:
    build:
      context: ./frontend
    container_name: office-frontend
    restart: always

  nginx:
    image: nginx:latest
    container_name: office-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - office-frontend
      - office-backend
    restart: always
