version: '3.8'

services:

  office-backend:
    image: 808872801655.dkr.ecr.ap-southeast-1.amazonaws.com/office-backend:latest
    container_name: office-backend
    ports:
      - "5000:5000"
    restart: always

  office-frontend:
    image: 808872801655.dkr.ecr.ap-southeast-1.amazonaws.com/office-frontend:latest
    container_name: office-frontend
    restart: always

  nginx:
    image: nginx:latest
    container_name: office-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - office-frontend
      - office-backend
    restart: always
